-- drop db if exists

-- create db if not exists

-- drop table if exists
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS hikes;

-- create USERS table if not exists
CREATE IF NOT EXISTS users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname TEXT,
  lastname TEXT,
  email TEXT,
  password TEXT,
)

-- create HIKES table if not exists
CREATE IF NOT EXISTS favoritehikes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  hike_id INT,
)