-- drop db if exists
DROP DATABASE IF EXISTS mvp;

-- create db if not exists (postgres does not support CREATE IF NOT EXISTS)
CREATE DATABASE mvp;

-- drop table if exists
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS hikes;

-- create USERS table if not exists
CREATE IF NOT EXISTS users (
  user_id INT GENERATED BY DEFAULT AS IDENTITY,
  email TEXT,
  password TEXT,
  PRIMARY KEY (user_id),
);

-- create HIKES table if not exists
CREATE IF NOT EXISTS favoritehikes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT,
  hike_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(user_id),
);